import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import nodeProcess from 'node:process';
import { fileURLToPath } from 'node:url';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const context = { window: {} };
vm.runInNewContext(fs.readFileSync(path.join(root, 'assets/js/site-config.js'), 'utf8'), context);
const c = context.window.SITE_CONFIG;
const outputArgument = nodeProcess.argv.find(arg => arg.startsWith('--out='));
const output = outputArgument ? path.resolve(root, outputArgument.slice(6)) : root;
if (output !== root && !output.startsWith(root + path.sep)) throw new Error('Output must be inside this workspace.');
fs.mkdirSync(output, { recursive: true });
if (nodeProcess.argv.includes('--indexable-preview')) c.production = true;
const esc = s => String(s).replace(/[&<>"']/g, t => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[t]));
const url = file => c.siteUrl.replace(/\/$/, '') + '/' + (file === 'index.html' ? '' : file);
const paths = {
  drop: '<path d="M12 3C9 8 5 11 5 15a7 7 0 0 0 14 0c0-4-4-7-7-12Z"/><path d="M8 15a4 4 0 0 0 4 4"/>',
  shield: '<path d="m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6l8-3Z"/><path d="m8 12 3 3 5-6"/>',
  pin: '<path d="M19 10c0 5-7 11-7 11S5 15 5 10a7 7 0 0 1 14 0Z"/><circle cx="12" cy="10" r="2"/>',
  bottle: '<path d="M10 3h4v4l2 3v11H8V10l2-3V3Z"/><path d="M8 12h8M8 17h8M10 5h4"/>',
  truck: '<path d="M3 5h11v12H3zM14 9h4l3 4v4h-7M14 13h7"/><circle cx="7" cy="18" r="2"/><circle cx="18" cy="18" r="2"/>',
  building: '<path d="M4 21V4h10v17M14 10h6v11M2 21h20M7 7h4M7 11h4M7 15h4M8 21v-3h3v3M17 13h1M17 17h1"/>',
  cup: '<path d="M5 9h12v6a5 5 0 0 1-5 5H10a5 5 0 0 1-5-5V9ZM17 10h2a3 3 0 0 1 0 6h-2M8 3v3M12 3v3M3 22h17"/>',
  event: '<path d="m5 20 4-14 9 9-13 5ZM12 3l1 3M18 4l-2 4M21 10h-4M10 13l3 3M7 17l2 2"/>',
  factory: '<path d="M3 21V10l6 3V8l6 4V3h4l2 18H3ZM7 17h1M12 17h1M17 17h1"/>',
  check: '<path d="m5 12 4 4L19 6"/>',
  arrow: '<path d="M4 12h16m-6-6 6 6-6 6"/>',
  clock: '<circle cx="12" cy="12" r="9"/><path d="M12 7v5l4 2"/>',
  people: '<circle cx="9" cy="8" r="3"/><path d="M3 21v-3a6 6 0 0 1 12 0v3M16 5a3 3 0 0 1 0 6M18 15a4 4 0 0 1 3 4v2"/>',
  leaf: '<path d="M20 3C8 2 2 8 6 16c8 4 14-2 14-13ZM4 21 16 8"/>',
  mail: '<rect x="3" y="5" width="18" height="14" rx="2"/><path d="m3 6 9 7 9-7"/>',
  phone: '<path d="m7 3 3 5-3 3c2 3 3 4 6 6l3-3 5 3-2 4C9 22 2 15 3 5l4-2Z"/>',
  star: '<path d="m12 3 3 6 7 1-5 5 1 7-6-3-6 3 1-7-5-5 7-1 3-6Z"/>',
  lab: '<path d="M9 3h6M10 3v7L4 20h16l-6-10V3M7 15h10"/>',
  label: '<path d="M3 3h8l10 10-8 8L3 11V3Z"/><circle cx="7" cy="7" r="1"/>',
  book: '<path d="M12 6c-3-3-6-3-10-2v15c4-1 7-1 10 2 3-3 6-3 10-2V4c-4-1-7-1-10 2v15"/>',
  heart: '<path d="M12 21 3 12C-2 4 7 0 12 7c5-7 14-3 9 5l-9 9Z"/>',
  globe: '<circle cx="12" cy="12" r="9"/><ellipse cx="12" cy="12" rx="4" ry="9"/><path d="M3 12h18M5 7h14M5 17h14"/>',
  layers: '<path d="m12 3 10 6-10 6L2 9l10-6ZM2 14l10 6 10-6M2 18l10 6 10-6"/>',
  chart: '<path d="M4 3v18h17M8 16v-4M13 16V8M18 16V5"/>',
  menu: '<path d="M4 6h16M4 12h16M4 18h16"/>',
  up: '<path d="m6 14 6-6 6 6"/>',
  plus: '<path d="M12 5v14M5 12h14"/>',
  facebook: '<path d="M14 21v-8h3l1-4h-4V7c0-1 1-2 2-2h2V2h-3c-3 0-5 2-5 5v2H7v4h3v8"/>',
  instagram: '<rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><path d="M17 7h.01"/>',
  linkedin: '<path d="M4 9v12M4 4h.01M9 21V9h4v2c4-4 7-1 7 3v7M13 11v10"/>',
  youtube: '<rect x="2" y="5" width="20" height="14" rx="4"/><path d="m10 9 5 3-5 3V9Z"/>',
  whatsapp: '<path d="M21 12a9 9 0 0 1-13 8l-5 1 1-5a9 9 0 1 1 17-4Z"/><path d="m8 7 2 3-1 1 4 4 1-1 3 2"/>'
};
const icon = (name, extra='') => `<svg class="icon ${extra}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[name] || paths.drop}</svg>`;
const logo = `<a class="brand" href="index.html"><img class="brand-logo" src="${esc(c.logo)}" alt="" width="360" height="240" decoding="async"><span><strong>${esc(c.name)}</strong><small>${esc(c.tagline)}</small></span><span class="sr-only">Home</span></a>`;
const nav = [['index.html','Home'],['about.html','About Us'],['products.html','Products'],['services.html','Services'],['custom-label.html','Custom Label'],['distributors.html','Distributors'],['contact.html','Contact']];
const button = (text, href='contact.html?enquiry=bulk#enquiry', style='primary') => `<a class="button button-${style}" href="${href}">${text==='Learn More'?'Learn More About Us':text}${icon('arrow')}</a>`;
const checks = items => `<ul class="check-list">${items.map(x=>`<li>${icon('check')}<span>${x}</span></li>`).join('')}</ul>`;
const image = (src, alt, cls='', eager=false, width=1536, height=1024) => {
 const tag = `<img src="assets/images/${src}" alt="${alt}" width="${width}" height="${height}" ${eager?'fetchpriority="high"':'loading="lazy"'} decoding="async" class="${cls}">`;
 return src==='hero/water-hero.webp'?`<picture class="hero-picture"><source media="(max-width: 767px)" srcset="assets/images/hero/water-hero-mobile.webp">${tag}</picture>`:tag;
};
const heading = (eyebrow,title,text='',center=false) => `<div class="section-heading ${center?'center':''}"><p class="eyebrow">${eyebrow}</p><h2>${title}</h2>${text?`<p>${text}</p>`:''}</div>`;
const section = (content,cls='',id='') => `<section class="section ${cls}"${id?` id="${id}"`:''}><div class="container">${content}</div></section>`;
const card = (title,description,i='drop',points=[]) => `<article class="feature-card"><span class="icon-badge">${icon(i)}</span><h3>${title}</h3><p>${description}</p>${points.length?checks(points):''}</article>`;
const stats = (items,home=false) => `<div class="stats-grid">${items.map(([n,label,i])=>`<div class="stat">${home?`<span class="icon-badge">${icon(i)}</span>`:''}<div><strong>${n}</strong><span>${label}</span></div></div>`).join('')}</div><p class="sample-note">Illustrative ${home?'service figures':'company figures'} — replace with verified business information.</p>`;
const process = (items) => `<ol class="process-grid">${items.map(([title,desc,i],n)=>`<li data-reveal><span class="step-number">0${n+1}</span><span class="icon-badge">${icon(i)}</span><h3>${title}</h3><p>${desc}</p></li>`).join('')}</ol>`;
const manufacture = [['Water Sourcing','Responsible sourcing begins the journey.','drop'],['Multi-Stage Purification','A carefully designed treatment sequence.','lab'],['Quality Testing','Checks throughout the production process.','shield'],['Automated Packaging','Sealed and prepared for dependable supply.','bottle']];
const services = [
 ['Corporate Offices','A water supply plan that works as hard as your team.','building',['Scheduled delivery','Volume pricing','GST invoices']],
 ['Restaurants & Hotels','Thoughtful presentation for every guest and every table.','cup',['Premium presentation','Flexible quantities','Coordinated fulfillment']],
 ['Events & Parties','Keep your guests refreshed, from the first arrival to the last.','event',['Event-based supply','Multiple bottle sizes','Custom branding options']],
 ['Industrial Supply','Practical hydration solutions for a busy working day.','factory',['High-volume requirements','Supply planning','Dedicated coordination']]
];
const productData = [
 {name:'250ml',size:'250 ml',desc:'Small bottle. Big convenience.',category:'small',image:'products/water-bottle-250ml.webp',points:['Compact & portable','Ideal for events']},
 {name:'500ml',size:'500 ml',desc:'Your everyday refreshment.',category:'small',image:'products/water-bottle-500ml.webp',points:['Easy to carry','Corporate favorite']},
 {name:'1 Liter',size:'1 liter',desc:'More hydration for your day.',category:'large',image:'products/water-bottle-1-liter.webp',points:['Extended hydration','Everyday versatility']},
 {name:'2 Liter',size:'2 liters',desc:'Made for sharing.',category:'large',image:'products/water-bottle-2-liter.webp',points:['Family & team use','Value packaging']},
 {name:'20L Jar',size:'20 liters',desc:'A workplace essential.',category:'jars',image:'products/water-jar-20-liter.webp',points:['Dispenser-friendly','Bulk supply option']},
 {name:'Gifting Bottles',size:'Custom formats',desc:'A refreshing finishing touch.',category:'gifting',image:'products/gifting-bottles.webp',points:['Elegant presentation','Custom label options']}
];
const products = (detailed=false) => `<div class="product-grid ${detailed?'product-grid-detailed':''}">${productData.map(p=>`<article class="product-card" data-category="${p.category}"><div class="product-image">${image(p.image,`${p.name} sample drinking water packaging`,'',false,640,640)}</div><div class="product-content"><p class="product-size">${p.size}</p><h3>${p.name}</h3><p>${p.desc}</p>${checks(p.points)}${button('Request Quote',`contact.html?enquiry=product&product=${encodeURIComponent(p.name)}#enquiry`,'outline')}</div></article>`).join('')}</div>`;
const customFeatures = ['Corporate branding','Event-specific labels','Wedding bottles','Hotel bottles','Company logo bottles','White-label manufacturing'];
const customSplit = () => `<div class="split custom-split"><div class="visual-frame">${image('custom-label/custom-branded-bottles.webp','Illustrative premium bottles with custom white, navy and gold labels')}</div><div>${heading('CUSTOM LABEL / WHITE LABEL','Make Your Brand<br>Stand Out','Make every sip a part of your story. Explore personalized water bottles for businesses, celebrations, hotels, and corporate gifting.')}${checks(customFeatures)}${button('Customize Your Bottle','custom-label.html')}</div></div>`;
const cta = (title='Ready to Partner With Us?', text="Let's build a reliable water supply solution for your business.", full=true) => section(`<div class="cta-panel"><div><p class="eyebrow">A CLEAR COMMITMENT TO YOUR BUSINESS</p><h2>${title}</h2><p>${text}</p></div><div class="button-row">${button('Request Bulk Pricing')}${full?button('Start Distribution Partnership','distributors.html','light')+button('Customize Your Bottle','custom-label.html','ghost'):''}</div></div>`,'cta-section');
const contactInfo = () => `<div class="contact-details">${[['phone','Call Us',c.phone],['mail','Email Us',c.email],['pin','Visit Us',c.address],['clock','Business Hours',c.hours]].map(([i,t,v])=>`<div class="contact-detail"><span class="icon-badge">${icon(i)}</span><div><h3>${t}</h3><p>${esc(v)}</p></div></div>`).join('')}</div>`;
let formCounter=0;
const field = (name,label,type='text',required=true,full=false,opts=null) => {
 const id=`f${formCounter}-${name}`; const attr=`id="${id}" name="${name}"${required?' required':''} aria-describedby="${id}-error"`;
 const autocomplete={full_name:'name',company:'organization',email:'email',phone:'tel',city:'address-level2',state:'address-level1',pincode:'postal-code',address:'street-address'}[name];
 const input = opts?`<select ${attr}><option value="">Select ${label.toLowerCase()}</option>${opts.map(([v,t])=>`<option value="${v}">${t}</option>`).join('')}</select>`:type==='textarea'?`<textarea ${attr} rows="4" minlength="10" maxlength="3000" placeholder="Tell us a little about your requirements…"${autocomplete?` autocomplete="${autocomplete}"`:''}></textarea>`:`<input ${attr} type="${type}"${autocomplete?` autocomplete="${autocomplete}"`:''}${name==='phone'?' inputmode="tel" maxlength="25"':name==='pincode'?' inputmode="numeric" pattern="[0-9]{6}" maxlength="6"':' maxlength="200"'}>`;
 return `<div class="form-field ${full?'full-width':''}"><label for="${id}">${label}${required?'<span aria-hidden="true"> *</span>':''}</label>${input}<span class="field-error" id="${id}-error"></span></div>`;
};
const form = (distributor=false) => {
 formCounter++;
 return `<form class="enquiry-form" data-enquiry-form data-kind="${distributor?'distributor':'contact'}" action="${esc(c.formEndpoint || '#')}" method="post" novalidate><h3>${distributor?'Distributor Registration':'Send Us a Message'}</h3><p class="form-intro">${distributor?'Tell us about your business and the area you would like to serve.':'A better water supply starts with a conversation.'}</p><p class="form-note">Fields marked * are required.${!c.formEndpoint?' Demo form: submission service is not connected.':''}</p><div class="form-grid">${field('full_name','Full Name')}${field('company','Company Name','text',false)}${field('email','Email Address','email')}${field('phone','Phone Number','tel')}${field('city','City / Location')}${distributor?field('state','State')+field('pincode','Pincode')+field('address','Address','textarea',true,true)+field('experience','Business Experience','text',true,true):field('enquiry_type','Enquiry Type','text',true,false,[['bulk','Bulk supply'],['product','Product quote'],['custom','Custom labels'],['distributor','Distribution partnership'],['general','General enquiry']])}${field('message',distributor?'Business Message':'Message / Requirements','textarea',true,true)}</div><div class="honeypot" aria-hidden="true"><label>Leave empty<input name="website" tabindex="-1" autocomplete="off"></label></div><input type="hidden" name="subject" value="${distributor?'Distribution partnership enquiry':'Water supply enquiry'}"><p class="form-privacy">By submitting, you agree to be contacted about this enquiry. <a href="#privacy" data-policy="privacy">Privacy policy</a></p><button class="button button-primary" type="submit">${distributor?'Submit Registration':'Send Enquiry'}${icon('arrow')}</button><p class="form-status" role="status" aria-live="polite" tabindex="-1"></p><noscript><p>Enable JavaScript to validate and send this form.</p></noscript></form>`;
};
const faqData = [
 ['What is the minimum order quantity?','Minimum quantities depend on the bottle format, delivery area, and branding requirements. Share your requirements to request a confirmed quotation.'],
 ['Do you offer custom labels?','This sample range includes custom-label options. The company should confirm available materials, artwork specifications, lead times, and quantities before an order is placed.'],
 ['Do you deliver outside the main city?','Delivery coverage is subject to the actual service network. Send your city and pincode so the team can confirm availability and delivery terms.'],
 ['Do you provide corporate pricing?','Ask for a quotation based on your estimated monthly quantity, preferred packaging, and delivery schedule. Pricing is confirmed individually.'],
 ['Can businesses become distributors?','Use the distributor enquiry form to express interest. Territory availability, eligibility, and commercial terms must be confirmed by the company.'],
 ['Do you provide bulk supply?','Bulk supply can be discussed for offices, hospitality, events, and industrial requirements. Capacity, schedules, and final terms require company confirmation.']
];
const faq = () => `<div class="faq-list">${faqData.map(([q,a],i)=>`<article class="faq-item"><h3><button class="faq-toggle" aria-expanded="false" aria-controls="faq-answer-${i}" id="faq-question-${i}">${q}${icon('plus')}</button></h3><div class="faq-answer" id="faq-answer-${i}" aria-labelledby="faq-question-${i}" hidden><p>${a}</p></div></article>`).join('')}</div>`;
const hero = (title,label,desc,photo='hero/water-hero.webp') => `<section class="page-hero"><div class="container page-hero-inner"><div><nav class="breadcrumb" aria-label="Breadcrumb"><a href="index.html">Home</a><span aria-hidden="true">/</span><span aria-current="page">${label}</span></nav><p class="eyebrow">PURE WATER. CLEAR COMMITMENT.</p><h1>${title}</h1><p>${desc}</p></div>${image(photo,'', 'page-hero-image',true)}</div></section>`;
const home = `<section class="home-hero"><div class="container hero-inner"><div class="hero-copy"><p class="eyebrow"><span class="eyebrow-line"></span>PURE · SAFE · TRUSTED</p><h1>Pure Mineral Water.<br><span>For a Healthier<br class="desktop-break"> Tomorrow.</span></h1><p>Premium packaged drinking water for corporates, hospitality, events, and large-scale distribution.</p><div class="button-row">${button('Get Bulk Quote')}${button('Become a Partner','distributors.html','outline')}</div><div class="hero-detail">${icon('drop')} Fresh thinking. Dependable hydration.</div></div>${image('hero/water-hero.webp','Clear water jar and blue-capped bottles surrounded by a fresh water splash','hero-image',true)}</div></section>
${section(stats(c.homeStats,true),'stats-section')}
${section(`<div class="split"><div class="visual-frame factory-frame">${image('about/water-manufacturing-facility.webp','Illustrative modern water manufacturing facility with landscaped grounds')}<div class="image-caption">${icon('shield')}<span>Quality at every step.<br><strong>Care in every bottle.</strong></span></div></div><div>${heading('ABOUT US','Your Trusted Enterprise<br>Water Supply Partner','From the office desk to the hotel table, great water should come with great service. Our sample supply model brings together carefully packaged water, considered presentation, and dependable logistics.')}${checks(['ISI certification details to be verified','Multi-stage purification process','Contract-based supply options','Dedicated account coordination'])}${button('Learn More','about.html','outline')}</div></div>`)}
${section(`<div class="heading-with-link">${heading('OUR PRODUCTS','Premium Water for Every Need','The right size. The right setting. The same clear commitment.') }<a class="text-link" href="products.html">View all products ${icon('arrow')}</a></div>${products()}`,'pale-section')}
${section(`${heading('ENTERPRISE SOLUTIONS','Corporate, Bulk & Industrial Supply','A considered supply solution for every kind of business.')}<div class="grid grid-4">${services.map(x=>card(...x)).join('')}</div>`)}
${section(customSplit(),'pale-section')}
${section(`${heading('THE PROCESS','From Nature to You','A thoughtful journey, with quality at its heart.',true)}${process(manufacture)}`)}
${section(`<div class="split"><div>${heading('RELIABLE LOGISTICS','Distribution & Logistics','Good service goes beyond the bottle. Plan a supply schedule around your business, with clear communication at every step.')}<div class="logistics-features">${[['truck','Own Fleet','Dedicated vehicles — sample service model'],['clock','Timely Fulfillment','Same-day / scheduled delivery, subject to confirmation'],['people','Distributor Support','Territory-based support options']].map(([i,t,d])=>`<div>${icon(i)}<span><strong>${t}</strong><small>${d}</small></span></div>`).join('')}</div>${button('Become a Distributor','distributors.html')}</div><div class="visual-frame">${image('distributors/delivery-truck.webp','Illustrative water delivery truck outside a modern facility')}</div></div>`,'pale-section')}
${section(`${heading('INDUSTRIES WE SERVE','Trusted Across Multiple Sectors','Hydration solutions shaped around the places people live, work, and connect.')}<div class="grid grid-3">${[['Corporate & IT','Keep workspaces and meeting rooms refreshed.','building'],['Hospitality & Tourism','A welcome detail in a memorable guest experience.','cup'],['Education & Training','Practical hydration for campuses and learning spaces.','book'],['Residential Complexes','Thoughtful supply planning for growing communities.','people'],['Retail & Distribution','A versatile range for stores and local partners.','bottle'],['Healthcare & Wellness','Considered water supply for care and wellness environments.','heart']].map(x=>card(...x)).join('')}</div>`)}
${section(`${heading('WHY CHOOSE US','The Right Choice for Your Water Needs','A partnership built around the details that matter.')}<div class="grid grid-5">${[['Enterprise Reliability','Supply planning around your operations.','shield'],['Premium Presentation','Packaging that feels at home in your business.','star'],['Scalable Operations','Options for everyday needs and larger requirements.','chart'],['Custom Branding','A bottle that carries your identity.','label'],['Local Support','A clear point of contact for your team.','people']].map(x=>card(...x)).join('')}</div>`,'pale-section')}
${cta()}
${section(`<div class="split contact-split"><div>${heading('LET’S TALK','Get In Touch','Tell us what your business needs. We will help you take the next step toward a considered water supply plan.')}${contactInfo()}</div>${form()}</div>`,'','enquiry')}`;
const values = [['Purity','Care in the product and clarity in the process.','drop'],['Integrity','Honest conversations and transparent commitments.','shield'],['Reliability','Consistency in the details that matter.','clock'],['Innovation','Better ways to package, plan, and serve.','lab'],['Partnership','Long-term thinking for shared progress.','people'],['Sustainability','Thoughtful use of materials and resources.','leaf'],['Excellence','A commitment to continual improvement.','star'],['Community','Local relationships at the heart of our work.','heart']];
const about = hero('About Us','About Us','Purity. Quality. Trust.','about/pristine-water-landscape.webp')+
section(`<div class="split"><div class="visual-frame">${image('about/water-manufacturing-facility.webp','Sample water manufacturing building and green facility grounds')}</div><div>${heading('OUR STORY','Pure Water.<br>A Healthier Future.')}<p>Water is a small part of the day that makes a meaningful difference. ${esc(c.name)} represents a simple idea: businesses deserve water that is carefully packaged and easy to source.</p><p>Our proposed model serves workplaces, hospitality teams, event organizers, and distribution partners. From choosing the right bottle to planning repeat deliveries, the emphasis is on thoughtful service and lasting relationships.</p><p class="sample-note">Company story is illustrative. Replace with your verified history and operating details.</p></div></div>`)+
section(`<div class="grid grid-2">${card('Our Mission','To make well-presented packaged water accessible to businesses through thoughtful products and clear, dependable service.','drop')}${card('Our Vision','To become a trusted regional supply partner, building lasting relationships through quality, care, and responsible growth.','globe')}</div>`,'pale-section')+
section(`${heading('A GROWING COMMITMENT','Our Company in Numbers')}${stats(c.aboutStats)}`)+
section(`${heading('OUR VALUES','What We Stand For','The principles behind the product and the partnership.')}<div class="grid grid-4">${values.map(x=>card(...x)).join('')}</div>`,'pale-section')+
section(`${heading('OUR JOURNEY','Every Step, a Clearer Purpose','Milestones shown as placeholders; add your actual dates and achievements.')}<ol class="journey">${['Company Founded','Facility Expansion','Distribution Growth','New Product Range','Regional Expansion'].map((x,i)=>`<li><span>0${i+1}</span><small>[Add year]</small><h3>${x}</h3></li>`).join('')}</ol>`)+
section(`${heading('CERTIFICATIONS / QUALITY','Trust Begins with Transparency','Certification details must be verified before publication. No certification is claimed by this sample website.')}<div class="grid grid-4">${[['Quality Certification','Add issuing body, certificate number, and validity.','shield'],['Food Safety','Add applicable license and verified food-safety details.','lab'],['ISI / BIS','Add valid license details where applicable.','bottle'],['Laboratory Testing','Add accredited laboratory reports and test dates.','check']].map(x=>card(...x)).join('')}</div>`,'pale-section')+
section(`<div class="facility-banner">${image('about/water-manufacturing-facility.webp','Illustrative modern water packaging facility')}<div>${heading('MANUFACTURING FACILITY','Clean Water.<br>Stronger Commitments.','Showcase your real treatment equipment, quality laboratory, packaging lines, and facility standards here.')}${button('Talk to Our Team','contact.html')}</div></div>`)+cta();
const productPage = hero('Our Products','Products','Premium packaging. Everyday refreshment.')+
section(`${heading('OUR PRODUCT RANGE','A Little Refreshment.<br>A World of Possibilities.','From compact event bottles to workplace jars, explore a sample range designed around the way your business serves water.')}<div class="filter-bar" role="group" aria-label="Filter products">${[['all','All'],['small','Small Bottles'],['large','Large Bottles'],['jars','Jars'],['gifting','Gifting']].map(([v,t],i)=>`<button class="filter-button ${i===0?'active':''}" data-filter="${v}" aria-pressed="${i===0?'true':'false'}">${t}</button>`).join('')}</div><p class="sr-only" id="filter-status" role="status" aria-live="polite"></p>${products(true)}<p class="sample-note">Illustrative product images. Confirm available formats, packaging specifications, and order quantities with the company.</p>`)+
section(`${heading('THE DETAILS MAKE THE DIFFERENCE','Thoughtfully Packaged. Ready for Your Business.')}<div class="grid grid-3">${card('Versatile Formats','Find an appropriate size for desks, tables, events, and shared spaces.','bottle')}${card('Considered Presentation','Clean packaging complements a professional guest and customer experience.','star')}${card('Supply That Fits','Discuss repeat orders, scheduled deliveries, and bulk quantities.','truck')}</div>`,'pale-section')+cta('Need a Custom Quantity or Special Packaging?','Let’s find the right bottle and supply plan for your business.',false);
const servicesPage = hero('Our Services','Services','Your business. Our clear commitment.')+
section(`${heading('BUSINESS WATER SOLUTIONS','Corporate, Bulk & Industrial Supply','Different businesses need different supply plans. Start with your requirements, and build a practical approach to packaging, quantities, and delivery.') }<div class="grid grid-2">${services.map(x=>card(...x)).join('')}${card('Bulk Water Supply','A coordinated supply option for recurring orders, larger teams, and high-volume events.','layers',['Bottle and jar options','Quantity-based quotations','Delivery terms agreed in advance'])}</div>`)+
section(`${heading('OUR SERVICE PROCESS','From Requirement to Refreshment','Four clear steps to a better supply partnership.',true)}${process([['Requirement','Tell us your quantity, format, location, and schedule.','mail'],['Quotation','Review the proposed pricing and supply terms.','book'],['Delivery','Agree on timing and fulfillment requirements.','truck'],['Long-Term Partnership','Refine your plan as your business grows.','people']])}`,'pale-section')+
section(`<div class="split"><div>${heading('BUILT FOR THE LONG TERM','A Partner in Your Everyday Operations','The best supply relationship makes the everyday feel easier. Discuss a recurring plan with a clear contact, agreed quantities, and a delivery rhythm that suits your business.')}${checks(['A clear point of contact','Requirement-based supply planning','Transparent commercial terms','Regular review of your supply needs'])}${button('Explore a Supply Partnership','contact.html?enquiry=bulk#enquiry')}</div><div class="visual-frame">${image('distributors/delivery-truck.webp','Sample delivery fleet serving business water supply')}</div></div>`)+cta('Let’s Discuss Your Requirements','A considered water supply solution starts with a simple conversation.',false);
const customPage = hero('Custom Label &<br>White-label Solutions','Custom Label','Your brand, beautifully bottled.','custom-label/custom-branded-bottles.webp')+
section(customSplit())+
section(`${heading('WHY CUSTOM BRANDING','A Small Detail. A Lasting Impression.','Make your brand a thoughtful part of the experience.')}<div class="grid grid-3">${[['Corporate Branding','Bring your identity to meeting rooms, events, and guest spaces.','building'],['Event Branding','Connect every touchpoint to the story of your event.','event'],['Wedding Branding','A personal finishing touch for your celebration.','heart'],['Hotel Branding','A considered welcome with your property’s identity.','cup'],['Retail Branding','Explore packaging for your own retail concept.','label'],['White-label Solutions','Discuss a product range built around your brand.','bottle']].map(x=>card(...x)).join('')}</div>`,'pale-section')+
section(`${heading('BRANDING OPTIONS','Made for Your Occasion','A clean label can carry a powerful identity. Explore the format that feels right for you.')}<div class="grid grid-4 branding-grid">${[['Corporate Bottles','Understated labels for a professional setting.'],['Event Bottles','A coordinated look for launches and celebrations.'],['Wedding Bottles','Personal details for a memorable day.'],['Hotel Bottles','A refined extension of your guest experience.']].map(([t,d])=>`<article class="branding-card">${image('custom-label/custom-branded-bottles.webp',`Illustrative custom water bottle designs for ${t.toLowerCase()}`)}<div><h3>${t}</h3><p>${d}</p></div></article>`).join('')}</div>`)+
section(`${heading('CUSTOM BOTTLE OPTIONS','Your Identity. Your Details.')}<div class="grid grid-3">${card('Bottle Format','Discuss compact bottles, everyday sizes, and premium gifting formats.','bottle')}${card('Label Design','Add your logo, brand colors, event message, and approved artwork.','label')}${card('Finishing & Quantities','Confirm materials, quantities, artwork approval, and production timelines.','layers')}</div><p class="sample-note">Options are illustrative and subject to actual manufacturing capability. Required product and regulatory information must remain on approved labels.</p>`,'pale-section')+
section(`${heading('HOW IT WORKS','From Your Idea to Your Bottle', '', true)}${process([['Share Your Brief','Choose an occasion, format, quantity, and date.','mail'],['Create Your Label','Share artwork or discuss your design requirements.','label'],['Approve the Details','Confirm the label proof, pricing, and production terms.','check'],['Plan Your Delivery','Agree on production and fulfillment timelines.','truck']])}`)+cta('Create Your Custom Label','Stand out with your own brand. Get in touch today.',false);
const distributorPage = hero('Become a Distributor','Distributors','A refreshing opportunity. A shared ambition.','distributors/delivery-truck.webp')+
section(`<div class="split"><div>${heading('WHY PARTNER WITH US?','Grow with a Clear Purpose','Explore a distribution partnership shaped around your market, your customers, and your business goals.')}${checks(['A versatile sample product range','Territory discussions based on availability','A dedicated point of contact','A plan for building local relationships'])}${button('Register Your Interest','#registration')}</div><div class="visual-frame">${image('distributors/delivery-truck.webp','Illustrative branded water distribution truck')}</div></div>`)+
section(`${heading('DISTRIBUTOR BENEFITS','Good Products. Better Partnerships.')}<div class="grid grid-4">${[['Attractive Margins','Discuss commercially viable pricing and partner terms.','chart'],['Growing Demand','Explore hydration requirements across business sectors.','globe'],['Brand Support','Discuss approved product and marketing materials.','label'],['Dedicated Team','A point of contact for your partnership enquiries.','people']].map(x=>card(...x)).join('')}</div>`,'pale-section')+
section(`<div class="split contact-split"><div>${heading('TAKE THE NEXT STEP','Let’s Build Something Together','Tell us about your business experience and the territory you would like to serve. Registration expresses interest and is subject to company review.')}${image('distributors/delivery-truck.webp','Sample water delivery truck for local distribution','rounded-image')}<p class="sample-note">No exclusivity, margins, or territory availability are guaranteed by this sample website.</p></div>${form(true)}</div>`,'','registration')+
section(`${heading('DISTRIBUTION NETWORK','Local Knowledge. Shared Reach.','Use this area to publish your verified service regions and partner network.')}<div class="network-panel">${icon('pin')}<div><h3>Hyderabad & Surrounding Regions</h3><p>Illustrative service area. Add confirmed territories and fulfillment locations before publishing.</p></div>${button('Enquire About Your Territory','contact.html?enquiry=distributor#enquiry','outline')}</div>`,'pale-section')+cta('Your Next Partnership Starts Here','Share your market knowledge. Explore the possibilities.',false);
const contactPage = hero('Contact Us','Contact','Good conversations. Clear solutions.')+
section(`<div class="split contact-split"><div>${heading('GET IN TOUCH','We’re Here to Help','Whether you’re planning an order, exploring custom labels, or building a distribution business, start the conversation here.')}${contactInfo()}<p class="sample-note">Contact information and business hours are placeholders.</p></div>${form()}</div>`,'','enquiry')+
section(`<div class="map-placeholder" role="img" aria-label="Placeholder for company location map"><div class="map-pin">${icon('pin')}</div><h2>Find Us in Hyderabad</h2><p>[Add verified facility address and map link]</p><small>Map placeholder — replace with your confirmed location.</small></div>`,'pale-section')+
section(`${heading('FREQUENTLY ASKED QUESTIONS','A Little More Clarity','Sample guidance. Final service details will be confirmed by the company.')} ${faq()}`)+cta('Find the Right Water Supply for Your Business','From first enquiry to your next order, let’s make it straightforward.',false);
const notfound = `<section class="section not-found"><div class="container"><span class="error-number">404</span><p class="eyebrow">LET’S GET YOU BACK ON TRACK</p><h1>Page Not Found</h1><p>The page you're looking for doesn't exist or may have moved.</p><div class="button-row">${button('Back to Home','index.html')}${button('View Products','products.html','outline')}${button('Contact Us','contact.html','outline')}</div></div></section>`;
const footer = `<footer class="site-footer"><div class="container"><div class="footer-grid"><div class="footer-company">${logo}<p>Thoughtfully packaged water.<br>Considered supply solutions.<br>A clear commitment to your business.</p><span class="footer-caption">ILLUSTRATIVE BUSINESS INFORMATION</span></div><div><h2>Quick Links</h2><ul>${nav.map(([f,t])=>`<li><a href="${f}">${t}</a></li>`).join('')}</ul></div><div><h2>Services</h2><ul><li><a href="services.html">Corporate Supply</a></li><li><a href="services.html">Hotels & Restaurants</a></li><li><a href="services.html">Events & Bulk Supply</a></li><li><a href="custom-label.html">Custom Label Bottles</a></li><li><a href="distributors.html">Distribution Partnership</a></li></ul></div><div><h2>Contact</h2><ul class="footer-contact"><li>${icon('phone')}${esc(c.phone)}</li><li>${icon('mail')}${esc(c.email)}</li><li>${icon('pin')}${esc(c.address)}</li></ul><h2 class="social-heading">Follow Us</h2><div class="social-links">${Object.entries(c.social).map(([k,v])=>`<a href="${esc(v)}" aria-label="${k[0].toUpperCase()+k.slice(1)}${v==='#'?' (link pending)':''}"${v==='#'?' data-placeholder-link':''}>${icon(k)}</a>`).join('')}</div></div></div><div class="footer-bottom"><p>© 2026 ${esc(c.name)}. All rights reserved.</p><div><a href="#privacy" data-policy="privacy">Privacy Policy</a><span aria-hidden="true">|</span><a href="#terms" data-policy="terms">Terms & Conditions</a></div></div></div></footer>`;
const policy = `<dialog class="policy-dialog" id="policy-dialog" aria-labelledby="policy-title"><div class="dialog-header"><h2 id="policy-title">Privacy Policy</h2><button class="dialog-close" aria-label="Close policy">×</button></div><div id="policy-content"></div></dialog>`;
const pages = [
 ['index.html','Premium Packaged Drinking Water','Premium packaged drinking water for offices, hospitality, events, custom labels, and distribution. Explore the Brahmagiri Aqua sample range.',home,'Home'],
 ['about.html','About Us — Purity, Quality & Trust','Discover the Brahmagiri Aqua sample company story, values, manufacturing approach, and commitment to thoughtful business water supply.',about,'About Us'],
 ['products.html','Water Bottles, Jars & Gifting Range','Explore 250ml, 500ml, 1 liter, 2 liter, 20L jars, and gifting bottle options. Request a quote for your business water requirements.',productPage,'Products'],
 ['services.html','Corporate, Hospitality & Bulk Water Supply','Explore sample water supply solutions for corporate offices, hotels, restaurants, events, and industrial requirements.',servicesPage,'Services'],
 ['custom-label.html','Custom Label & White-label Water Bottles','Explore custom water bottle label options for corporate branding, events, weddings, hospitality, gifting, and white-label supply.',customPage,'Custom Label'],
 ['distributors.html','Become a Water Distribution Partner','Express interest in an Brahmagiri Aqua distribution partnership. Explore the sample product range, partner benefits, and registration form.',distributorPage,'Distributors'],
 ['contact.html','Contact Us & Request a Bulk Quote','Enquire about packaged water, bulk supply, custom labels, and distribution opportunities through the Brahmagiri Aqua contact form.',contactPage,'Contact'],
 ['404.html','Page Not Found','Find your way back to Brahmagiri Aqua products, business supply solutions, and contact information.',notfound,'Page Not Found']
];
function structured(file,label){
 if(!c.production || c.siteUrl.includes('example.com') || file==='404.html') return '';
 const data=[{'@context':'https://schema.org','@type':'Organization','@id':url('index.html')+'#organization',name:c.name,url:url('index.html'),logo:url(c.logo)}];
 if(!c.phone.startsWith('[')) data[0].telephone=c.phone;
 if(!c.email.startsWith('[')) data[0].email=c.email;
 const social=Object.values(c.social).filter(x=>x.startsWith('https://'));if(social.length)data[0].sameAs=social;
 if(file!=='index.html') data.push({'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Home',item:url('index.html')},{'@type':'ListItem',position:2,name:label,item:url(file)}]});
 return data.map(x=>`<script type="application/ld+json">${JSON.stringify(x).replace(/</g,'\\u003c')}</script>`).join('');
}
for(const [file,title,rawDescription,body,label] of pages){
 const desc = rawDescription.replaceAll('Brahmagiri Aqua', c.name);
 const header=`<header class="site-header"><div class="container header-inner">${logo}<button class="menu-toggle" aria-label="Open navigation" aria-expanded="false" aria-controls="primary-nav">${icon('menu')}</button><nav id="primary-nav" class="primary-nav" aria-label="Primary navigation"><ul>${nav.map(([f,t])=>`<li><a href="${f}"${f===file?' class="active" aria-current="page"':''}>${t}</a></li>`).join('')}</ul>${button('Get Bulk Quote')}</nav></div></header><div class="menu-backdrop" hidden></div>`;
 const html=`<!doctype html>\n<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#06345b"><title>${esc(title)} | ${esc(c.name)}</title><meta name="description" content="${esc(desc)}"><meta name="robots" content="${c.production && file!=='404.html'?'index, follow':'noindex, follow'}"><link rel="canonical" href="${esc(url(file))}"><meta property="og:type" content="website"><meta property="og:site_name" content="${esc(c.name)}"><meta property="og:title" content="${esc(title)} | ${esc(c.name)}"><meta property="og:description" content="${esc(desc)}"><meta property="og:url" content="${esc(url(file))}"><meta property="og:image" content="${esc(url('assets/images/hero/open-graph.webp'))}"><meta property="og:image:alt" content="Premium water bottles in a fresh blue water splash"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${esc(title)} | ${esc(c.name)}"><meta name="twitter:description" content="${esc(desc)}"><meta name="twitter:image" content="${esc(url('assets/images/hero/open-graph.webp'))}"><link rel="icon" type="image/png" href="assets/icons/favicon-192.png"><link rel="manifest" href="site.webmanifest"><link rel="preload" href="assets/fonts/manrope-latin.woff2" as="font" type="font/woff2" crossorigin><link rel="stylesheet" href="assets/css/style.css">${structured(file,label)}<script src="assets/js/site-config.js" defer></script><script src="assets/js/main.js" defer></script>${file==='products.html'?'<script src="assets/js/products.js" defer></script>':''}${['index.html','contact.html','distributors.html'].includes(file)?'<script src="assets/js/contact.js" defer></script>':''}</head><body><a class="skip-link" href="#main">Skip to main content</a>${header}<main id="main">${body}</main>${footer}<button class="back-to-top" aria-label="Back to top" hidden>${icon('up')}</button>${policy}<div class="placeholder-status sr-only" role="status" aria-live="polite"></div></body></html>\n`;
 fs.writeFileSync(path.join(output,file),html);
}
fs.writeFileSync(path.join(output,'robots.txt'),`User-agent: *\n${c.production?'Allow: /':'Disallow: /'}\nSitemap: ${url('sitemap.xml')}\n`);
fs.writeFileSync(path.join(output,'sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${pages.filter(x=>x[0]!=='404.html').map(([f])=>`  <url><loc>${esc(url(f))}</loc></url>`).join('\n')}\n</urlset>\n`);
fs.writeFileSync(path.join(output,'site.webmanifest'),JSON.stringify({name:c.name,short_name:c.name,start_url:'./',display:'standalone',background_color:'#ffffff',theme_color:'#06345b',icons:[{src:'assets/icons/favicon-192.png',sizes:'192x192',type:'image/png',purpose:'any'},{src:'assets/icons/favicon-512.png',sizes:'512x512',type:'image/png',purpose:'any'}]},null,2));
console.log('Generated all 8 HTML pages, robots.txt, sitemap.xml, and manifest.');
